opencv/opencv_zoo

.gitignore
README.md
benchmark/README.md
benchmark/benchmark.py
benchmark/config/face_detection_yunet.yaml
benchmark/config/text_detection_db.yaml
benchmark/config/text_recognition_crnn.yaml
benchmark/data/.gitignore
benchmark/download.py
benchmark/requirements.txt
models/__init__.py
models/face_detection_yunet/LICENSE
models/face_detection_yunet/README.md
models/face_detection_yunet/demo.py
models/face_detection_yunet/face_detection_yunet.onnx
models/face_detection_yunet/yunet.py
models/text_detection_db/LICENSE
models/text_detection_db/README.md
models/text_detection_db/db.py
models/text_detection_db/demo.py
models/text_detection_db/text_detection_db.onnx
models/text_recognition_crnn/LICENSE
models/text_recognition_crnn/README.md
models/text_recognition_crnn/crnn.py
models/text_recognition_crnn/demo.py
models/text_recognition_crnn/text_recognition_crnn.onnx

Benchmark framework implementation and add YuNet for face detection, DB for text detection, CRNN for text recognition

---

benchmark/README.md
benchmark/benchmark.py
benchmark/config/face_detection_yunet.yaml
benchmark/config/text_detection_db.yaml
benchmark/config/text_recognition_crnn.yaml
benchmark/download_data.py

Improve benchmark configurations

---

benchmark/benchmark.py
benchmark/config/face_detection_yunet.yaml
benchmark/config/face_recognition_sface.yaml
benchmark/config/human_segmentation_pphumanseg.yaml
benchmark/config/image_classification_ppresnet.yaml
benchmark/config/qrcode_wechatqrcode.yaml
benchmark/config/text_detection_db.yaml
benchmark/config/text_recognition_crnn.yaml
benchmark/utils/__init__.py
benchmark/utils/dataloaders/__init__.py
benchmark/utils/dataloaders/base.py
benchmark/utils/dataloaders/base_dataloader.py
benchmark/utils/dataloaders/classification.py
benchmark/utils/dataloaders/recognition.py
benchmark/utils/dataloaders/tracking.py
benchmark/utils/factory.py
benchmark/utils/metrics/base.py
benchmark/utils/metrics/base_metric.py
benchmark/utils/metrics/detection.py
benchmark/utils/metrics/recognition.py

This PR is required by https://github.com/opencv/opencv_zoo/pull/15.

Decoupling dataloader and benchmark runner

---

README.md
benchmark/config/person_reid_youtureid.yaml
benchmark/download_data.py
models/__init__.py
models/person_reid_youtureid/LICENSE
models/person_reid_youtureid/README.md
models/person_reid_youtureid/demo.py
models/person_reid_youtureid/person_reid_youtu_2021nov.onnx
models/person_reid_youtureid/youtureid.py

Add YoutuReID for person ReID

---

README.md

Benchmarks are done with the code from https://github.com/fengyuentau/opencv_zoo_cpp.
cc @ShiqiYu @vpisarev @kaingwade @zihaomu

Add hardware: Allwinner D1 (Xuantie C906 CPU, RISC-V)

---

benchmark/config/image_classification_ppresnet.yaml
models/image_classification_ppresnet/demo.py
models/image_classification_ppresnet/image_classification_ppresnet50_2021oct.onnx
models/image_classification_ppresnet/image_classification_ppresnet50_2022jan.onnx

Update PP-ResNet50: Quantization ready

---

models/face_detection_yunet/demo.py
models/face_detection_yunet/yunet.py
models/face_recognition_sface/demo.py
models/human_segmentation_pphumanseg/demo.py
models/human_segmentation_pphumanseg/pphumanseg.py
models/image_classification_ppresnet/demo.py
models/image_classification_ppresnet/ppresnet.py
models/person_reid_youtureid/demo.py
models/person_reid_youtureid/youtureid.py
models/text_detection_db/db.py
models/text_detection_db/demo.py
models/text_recognition_crnn/crnn.py
models/text_recognition_crnn/demo.py

Available targets: CPU (default), CUDA, NPU
Available backends: OPENCV (default), CUDA, TIMVX

Add options for demo scripts to select backend & targets

---

README.md
benchmark/config/image_classification_mobilenetv1.yaml
benchmark/config/image_classification_mobilenetv2.yaml
models/__init__.py
models/image_classification_mobilenet/LICENSE
models/image_classification_mobilenet/README.md
models/image_classification_mobilenet/demo.py
models/image_classification_mobilenet/image_classification_mobilenetv1_2022apr-act_int8-wt_int8-quantized.onnx
models/image_classification_mobilenet/image_classification_mobilenetv1_2022apr.onnx
models/image_classification_mobilenet/image_classification_mobilenetv2_2022apr-act_int8-wt_int8-quantized.onnx
models/image_classification_mobilenet/image_classification_mobilenetv2_2022apr.onnx
models/image_classification_mobilenet/imagenet_labels.txt
models/image_classification_mobilenet/mobilenet_v1.py
models/image_classification_mobilenet/mobilenet_v2.py
tools/quantize/quantize.py
tools/quantize/transform.py

NOTE: these models are licensed under BSD-3-Clause License.

Add MobileNet v1 & v2

---

README.md
benchmark/config/license_plate_detection_yunet.yaml
benchmark/download_data.py
models/__init__.py
models/license_plate_detection_yunet/LICENSE
models/license_plate_detection_yunet/README.md
models/license_plate_detection_yunet/demo.py
models/license_plate_detection_yunet/license_plate_detection_lpd_yunet_2022may-int8-quantized.onnx
models/license_plate_detection_yunet/license_plate_detection_lpd_yunet_2022may.onnx
models/license_plate_detection_yunet/lpd_yunet.py
tools/quantize/inc_configs/lpd_yunet.yaml
tools/quantize/quantize-inc.py
tools/quantize/quantize-ort.py

Add LPD_YuNet for License Plate Detection

---

README.md

This PR updates benchmarking results on arm platforms (Raspberry PI specially in the zoo) for the optimization done in https://github.com/opencv/opencv/pull/21910.

Update benchmarking results on arm platform (RPI-CPU)

---

models/face_detection_yunet/README.md

Fixes https://github.com/opencv/opencv_zoo/issues/116

Update YuNet note with specification of detectable face sizes

---

models/face_recognition_sface/README.md

Fixes #107 
Updated SFace README.md notes to indicate used model and add link to reference paper.
Signed-off-by: Helio Perroni Filho <xperroni@gmail.com>

Updated SFace README.md notes

---

benchmark/color_table.svg
benchmark/generate_table.py

Change opencv_zoo links from master to main, since the branch name was changed

Change links of table from 'master' to 'main'

---

models/optical_flow_estimation_raft/BSD-3-LICENSE.txt
models/optical_flow_estimation_raft/MITLICENSE.txt
models/optical_flow_estimation_raft/README.md
models/optical_flow_estimation_raft/demo.py
models/optical_flow_estimation_raft/example_outputs/result.jpg
models/optical_flow_estimation_raft/example_outputs/vis.png
models/optical_flow_estimation_raft/optical_flow_estimation_raft_2023aug.onnx
models/optical_flow_estimation_raft/optical_flow_estimation_raft_2023jul.onnx
models/optical_flow_estimation_raft/raft.py

Adding RAFT in ONNX to the OpenCV model zoo.

Google Summer of Code: Adding RAFT Optical Flow Model using ONNX Format

---

models/object_tracking_vittrack/LICENSE
models/object_tracking_vittrack/README.assets/vittrack_demo.gif
models/object_tracking_vittrack/README.md
models/object_tracking_vittrack/demo.py
models/object_tracking_vittrack/example_outputs/vittrack_demo.gif
models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx

I made a mistake, the model here is the best model.

upload model mistake

---

models/pose_estimation_mediapipe/CMakeLists.txt
models/pose_estimation_mediapipe/README.md
models/pose_estimation_mediapipe/demo.cpp

pose estimation mediapipe in c++

Pose estimation mp

---

models/face_detection_yunet/demo.py
models/face_detection_yunet/yunet.py

Relates https://github.com/opencv/opencv_zoo/issues/31#issuecomment-1803107438

fix nontype error

---

benchmark/README.md
benchmark/color_table.svg
benchmark/table_config.yaml

Currently we have problem with NPU drivers (not opencv issues). After it is figured out we will add results on the NPU Ascend 310B.

add benchmark results on Atlas 200I DK A2

---

models/object_detection_yolox/demo.cpp

Minor PR to add missing save functionality to the YOLOX C++ demo. Issue was pointed out in https://github.com/opencv/opencv_zoo/issues/135#issuecomment-1962323969.

Add YOLOX C++ demo save functionality

---

models/face_image_quality_assessment_ediffiqa/LICENSE
models/face_image_quality_assessment_ediffiqa/README.md
models/face_image_quality_assessment_ediffiqa/demo.py
models/face_image_quality_assessment_ediffiqa/ediffiqa.py
models/face_image_quality_assessment_ediffiqa/ediffiqa_tiny_jun2024.onnx
models/face_image_quality_assessment_ediffiqa/example_outputs/demo.jpg
models/face_image_quality_assessment_ediffiqa/quality_distribution.png

The pull request adds a new face image quality assessment method to the OpenCV ZOO library. The implemented model is based on a mobilefacenet backbone for efficiency, while maintaining the superb results (of the larger models) presented in the original [paper](https://lmi.fe.uni-lj.si/wp-content/uploads/2024/03/TBIOM___DifFIQAv2.pdf).

Adding eDifFIQA(T) a light-weight model for face image quality assessment.

---

models/license_plate_detection_yunet/lpd_yunet.py

Fixes https://github.com/opencv/opencv_zoo/issues/292#issuecomment-2841342795

fix: set backend and target in init
