opencv/opencv_zoo

- README.md
This PR adds hardware `GPU CUDA: Jetson Nano` into the benchmark.
> Add hardware GPU CUDA: Jetson Nano

- models/face_detection_yunet/demo.py
- models/face_recognition_sface/demo.py
- models/human_segmentation_pphumanseg/demo.py
- models/image_classification_ppresnet/demo.py
- models/text_detection_db/demo.py
- models/text_recognition_crnn/demo.py
related issue https://github.com/opencv/opencv_zoo/issues/10
> Correct default values of model filenames in demo scripts

- benchmark/benchmark.py
- benchmark/config/face_detection_yunet.yaml
- benchmark/config/face_recognition_sface.yaml
- benchmark/config/human_segmentation_pphumanseg.yaml
- benchmark/config/image_classification_ppresnet.yaml
- benchmark/config/qrcode_wechatqrcode.yaml
- benchmark/config/text_detection_db.yaml
- benchmark/config/text_recognition_crnn.yaml
- benchmark/requirements.txt
- benchmark/utils/__init__.py
- benchmark/utils/factory.py
- benchmark/utils/metrics/__init__.py
- benchmark/utils/metrics/base.py
- benchmark/utils/metrics/base_metric.py
- benchmark/utils/metrics/detection.py
- benchmark/utils/metrics/recognition.py
- benchmark/utils/timer.py
This PR is created for the incoming object tracking models and benchmarking.
> Decoupling metrics from benchmark to allow different kinds of forward process

- README.md
- benchmark/benchmark.py
- benchmark/config/object_tracking_dasiamrpn.yaml
- benchmark/download_data.py
- benchmark/utils/dataloaders/base_dataloader.py
- benchmark/utils/dataloaders/tracking.py
- benchmark/utils/metrics/__init__.py
- benchmark/utils/metrics/tracking.py
- models/__init__.py
- models/object_tracking_dasiamrpn/LICENSE
- models/object_tracking_dasiamrpn/README.md
- models/object_tracking_dasiamrpn/dasiamrpn.py
- models/object_tracking_dasiamrpn/demo.py
- models/object_tracking_dasiamrpn/object_tracking_dasiamrpn_kernel_cls1_2021nov.onnx
- models/object_tracking_dasiamrpn/object_tracking_dasiamrpn_kernel_r1_2021nov.onnx
- models/object_tracking_dasiamrpn/object_tracking_dasiamrpn_model_2021nov.onnx
This PR depends on https://github.com/opencv/opencv_zoo/pull/14 for the benchmark implementation.
> Add DaSiamRPN for object tracking

- README.md
Make it easier to see benchmark results.
> Bring the table of results to the front

- README.md
Basically rename hardware setups to `<board/brand_name>-<processing_unit>`, such as `RPI-CPU` for the ARM CPU on Rasberry Pi, `INTEL-CPU` for the Intel CPU.
> Improve hardware namings on the table of benchmark results

- README.md
- benchmark/config/face_detection_yunet.yaml
- benchmark/config/face_recognition_sface.yaml
- benchmark/download_data.py
- models/image_classification_ppresnet/demo.py
> Fixes on 2021-12-15

- models/face_detection_yunet/face_detection_yunet_2021dec-act_int8-wt_int8-quantized.onnx
- models/face_recognition_sface/face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx
- models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2021oct-act_int8-wt_int8-quantized.onnx
- models/image_classification_ppresnet/image_classification_ppresnet50_2022jan-act_int8-wt_int8-quantized.onnx
- models/person_reid_youtureid/person_reid_youtu_2021nov-act_int8-wt_int8-quantized.onnx
- models/text_recognition_crnn/text_recognition_CRNN_CN_2021nov-act_int8-wt_int8-quantized.onnx
- models/text_recognition_crnn/text_recognition_CRNN_EN_2021sep-act_int8-wt_int8-quantized.onnx
- tools/quantize/README.md
- tools/quantize/quantize.py
- tools/quantize/requirements.txt
- tools/quantize/transform.py
| Model | Quantized? | Correctness | NOTE |
| ------ | ----------- | ------------- | --------- |
| YuNet |  ✓ | Passed | AP on WiderFace Val: E:0.827, M:0.820, H: 0.709 (drops ~0.02) |
| SFace | ✓ | Passed | Accuracy on LFW: 0.815 (drops about ~0.005) |
| PP-HumanSeg | ✓ |  | |
| PP-ResNet50 | ✓ | | |
| DaSiamRPN | x | | |
| YoutuReID | ✓ | | |
| WeChatQRCode | x | | Tiny enough and won't be quantized |
| DB-EN | x | | Some nodes failed after quantization |
| DB-CN | x | | Some nodes failed after quantization |
| CRNN-EN | ✓ | | |
| CRNN-CN | ✓ | | |
> Add tools for quantization and quantized models

- README.md
- benchmark/benchmark.py
> Add hardware: Khadas VIM3 & update benchmarks

- benchmark/config/image_classification_mobilenetv1.yaml
- benchmark/config/image_classification_mobilenetv2.yaml
- benchmark/config/image_classification_ppresnet.yaml
- models/image_classification_mobilenet/README.md
- models/image_classification_mobilenet/mobilenet_v1.py
- models/image_classification_mobilenet/mobilenet_v2.py
- models/image_classification_ppresnet/README.md
- models/image_classification_ppresnet/ppresnet.py
- tools/eval/README.md
- tools/eval/datasets/__init__.py
- tools/eval/datasets/imagenet.py
- tools/eval/eval.py
Note: the accuracy of PP-ResNet quantized is very low, which seems to be bad quantization.
> Add scripts to evaluate models in the zoo on different datasets

- models/face_detection_yunet/README.md
- tools/eval/README.md
- tools/eval/datasets/__init__.py
- tools/eval/datasets/widerface.py
- tools/eval/eval.py
The script is modified based on [WiderFace-Evaluation](https://github.com/wondervictor/WiderFace-Evaluation).
> Add script to evaluate face detection by WIDERFace

- tools/quantize/quantize-ort.py
Since onnxruntime==1.11.0, quantize_static.quant_format is set to QuantFormat.QDQ by default, which produces fake quantizated models. Explicitly setting it to QuantFormat.QOperator solves this problem.
> Use QuantFormat.QOperator by default to avoid fake quantization

- models/text_recognition_crnn/demo.py
The text recognition CRNN demo.py argument parser is incomplete.
Running
```
python3 demo.py --input ./examples/demo.jpg
```
yields the following error:
```
Traceback (most recent call last):
File "opencv_zoo/models/text_recognition_crnn/demo.py", line 75, in <module>
image = cv.resize(image, [args.width, args.height])
AttributeError: 'Namespace' object has no attribute 'width'
```
Error is caused by incomplete copy&paste of the argument parser of the `demo.py` in the text detection example.
This pull request fixes that.
> text_recognition example argparse bug fix

- benchmark/README.md
- benchmark/benchmark.py
- tools/quantize/requirements.txt
- Add the command for setting `PYTHONPATH` in powershell
- Let benchmark use the last path of environment
- Intel neural-compressor need  `onnxruntime-extensions`
> Update benchermark and quantize

- models/object_detection_yolox/yolox.py
Fix variable name error in yolox.py/setBackend
> Fix variable name error in yolox.py/setBackend

- README.md
- models/handpose_estimation_mediapipe/README.md
- models/handpose_estimation_mediapipe/handpose_estimation_mediapipe_2022may-int8-quantized.onnx
- models/license_plate_detection_yunet/license_plate_detection_lpd_yunet_2022may-int8-quantized.onnx
- models/palm_detection_mediapipe/README.md
- models/palm_detection_mediapipe/palm_detection_mediapipe_2022may-int8-quantized.onnx
- tools/quantize/inc_configs/lpd_yunet.yaml
- tools/quantize/inc_configs/mp_handpose.yaml
- tools/quantize/inc_configs/mp_palmdet.yaml
After re-quantizing these models, the benchmark results are changed on KV3-NPU:
`LPD-YuNet`: 154.20 -> 29.53
`MP-PalmDet`: 145.56 -> 62.45
`MP-HandPose`: 663.77 -> 42.7
> Re-quantify some models from per_channel mode to per_tensor mode

- models/object_detection_yolox/README.md
- models/object_detection_yolox/yolox.py
When there are no acceptable objects in the image, yolox returns 8400 results. This PR fixes this problem.
> Fix a bug in yolox when there are no acceptable objects

- README.md
- benchmark/config/object_detection_nanodet.yaml
- benchmark/config/object_detection_yolox.yaml
- benchmark/download_data.py
- models/__init__.py
- models/object_detection_nanodet/README.md
- models/object_detection_nanodet/nanodet.py
- models/object_detection_yolox/README.md
> Data and benchmarking for the new object detection models

- tools/eval/eval.py
Resolves #125 
This is caused by an extra key present in the `models` dictionary in `tools/eval/eval.py`
removing this key fixes the issue, the CRNN constructor does not expect a `charsetPath` argument.
The script runs successfully after this change.
output of `python eval.py -m crnn -d icdar -dr /path/to/icdar` : 
Evaluating CRNN with ICDAR val set: 100%|█████████████████████████████████████████████████████████████████████████| 1156/1156 [00:24<00:00, 46.52it/s]
Accuracy: 81.66%
> removed extra key in models.crnn dictionary

- README.md
- models/facial_expression_recognition/README.md
- models/facial_expression_recognition/demo.py
- models/facial_expression_recognition/facial_expression_recognition_mobilefacenet_2022july-int8-quantized.onnx
- tools/quantize/inc_configs/fer.yaml
This PR try to quantize `FER` model in `per_tensor` mode. Since the accuracy evaluation dataset has 350 images, the quantize loss should be relaxed. I changed it from `0.01` to `0.02` and then got a acceptable quantized model. 
The accuracy of the current model in the quantize evaluation dataset is `int8|fp32: 0.7457|0.7571`, which is only droped a little. But the time cost in `KV3-NPU` is changed **from 108.53ms to 29.80ms**!
> Update FER quantized model and fix document

- tools/eval/datasets/icdar.py
- tools/eval/datasets/iiit5k.py
- tools/eval/datasets/imagenet.py
This PR moves the `pbar.set_description` line outside of the for loop as discussed [here](https://github.com/opencv/opencv_zoo/pull/130#discussion_r1105252865) in  the following evaluation scripts : 
- [icdar.py](https://github.com/opencv/opencv_zoo/blob/6c68bc48c6f96042b29b3425174e431ccac38376/tools/eval/datasets/icdar.py#L37)
- [imagenet.py](https://github.com/opencv/opencv_zoo/blob/6c68bc48c6f96042b29b3425174e431ccac38376/tools/eval/datasets/imagenet.py#L43)
- [iiitk5.py](https://github.com/opencv/opencv_zoo/blob/6c68bc48c6f96042b29b3425174e431ccac38376/tools/eval/datasets/iiit5k.py#L40)
> move setting description outside for loop in evaluation scripts

- models/handpose_estimation_mediapipe/mp_handpose.py
This PR try to fix conner cases shown below: after rotateing hand, there are some pixels may affect the result will be lost.
By the way, pre-croping the image to a range of interest (RoI) may accelerate preprocess when original image is too large.
> Update hadnpose preprocess

- models/human_segmentation_pphumanseg/demo.py
- models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2021oct-act_int8-wt_int8-quantized.onnx
- models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2021oct.onnx
- models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2023mar-act_int8-wt_int8-quantized.onnx
- models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2023mar.onnx
- tools/quantize/quantize-ort.py
The model is downloaded following instructions from https://github.com/opencv/opencv/tree/4.x/samples/dnn/dnn_model_runner/dnn_conversion/paddlepaddle#2-run-paddleseg-portrait-segmentation-using-opencv
The model is ported from PaddlePaddle to ONNX with the following command:
```shell
paddle2onnx --model_dir humanseg_hrnet18_small_v1 \
--model_filename model.pdmodel \
--params_filename model.pdiparams \
--opset_version 11 \
--save_file humanseg_hrnet18_tiny.onnx
```
paddle2onnx          1.0.5
paddlepaddle         2.4.1
And simplified with:
```shell
onnxsim --input-shape="1,3,192,192" humanseg_hrnet18_tiny.onnx human_segmentation_pphumanseg_2023mar.onnx
```
onnxsim 0.4.17
> replace pphumanseg with a simplified one

- README.md
- benchmark/benchmark.py
Known issues:
- https://github.com/opencv/opencv_zoo/issues/136, almost fixed by https://github.com/opencv/opencv/pull/23319
- Integrated APIs such as FaceDetectorYN, setting backend and target separately fails. Possible solution is make an API in those wrapper classes like `setBackendAndTarget(backend_id, target_id)` in place of `setBackend` and `setTarget`.
Next PR:
- Limit the combination of backends and targets.
> Update benchmark and results for CANN backend

- README.md
- benchmark/README.md
- benchmark/benchmark.py
- benchmark/config/face_detection_yunet.yaml
- benchmark/config/face_recognition_sface.yaml
- benchmark/config/facial_expression_recognition.yaml
- benchmark/config/handpose_estimation_mediapipe.yaml
- benchmark/config/human_segmentation_pphumanseg.yaml
- benchmark/config/image_classification_mobilenet.yaml
- benchmark/config/image_classification_ppresnet.yaml
- benchmark/config/license_plate_detection_yunet.yaml
- benchmark/config/object_detection_nanodet.yaml
- benchmark/config/object_detection_yolox.yaml
- benchmark/config/object_tracking_dasiamrpn.yaml
- benchmark/config/palm_detection_mediapipe.yaml
- benchmark/config/person_reid_youtureid.yaml
- benchmark/config/qrcode_wechatqrcode.yaml
- benchmark/config/text_detection_db.yaml
- benchmark/config/text_recognition_crnn.yaml
- benchmark/utils/metrics/base.py
- benchmark/utils/metrics/base_metric.py
- benchmark/utils/metrics/detection.py
- benchmark/utils/metrics/recognition.py
- benchmark/utils/metrics/tracking.py
- models/handpose_estimation_mediapipe/mp_handpose.py
- models/image_classification_mobilenet/mobilenet.py
- models/object_detection_nanodet/nanodet.py
- models/object_detection_yolox/yolox.py
Changes:
```shell
$ python benchmark.py --cfg ./config/face_detection_yunet.yaml
mean=1.17, median=1.19, min=1.06, input size=[160, 120], model: YuNet with ['face_detection_yunet_2022mar.onnx']
mean=8.66, median=8.96, min=8.17, input size=[640, 480], model: YuNet with ['face_detection_yunet_2022mar.onnx']
mean=1.37, median=1.48, min=1.06, input size=[160, 120], model: YuNet with ['face_detection_yunet_2022mar-act_int8-wt_int8-quantized.onnx']
mean=10.96, median=11.17, min=8.17, input size=[640, 480], model: YuNet with ['face_detection_yunet_2022mar-act_int8-wt_int8-quantized.onnx']
```
```shell
$ python benchmark.py --all --model_exclude license_plate_detection_lpd_yunet_2023mar_int8.onnx:human_segmentation_pphumanseg_2023mar_int8.onnx
Benchmarking ...
backend=cv.dnn.DNN_BACKEND_OPENCV …
```
> Refactor benchmark

- benchmark/README.md
- benchmark/color_table.svg
- benchmark/generate_table.py
- benchmark/table_config.yaml
Update the color table:
- Automatically parse table data based on benchmark results
- Remove `(ms)` from the header
- Make color changes non-linear
- Header device direct to detail url
- Models name direct to detail url
- Split device companpy from device mdoel
- Make header text bold and center alignment
- Make color map be in the center of the table
- Add a config file for the parser:
- acceptable_time: values greater than this will be set to red. I use the value of 100 times the best result
- need other information for the parser
TODO: need @fengyuentau rename devices display_info
> update generate table script

- models/text_recognition_crnn/text_recognition_CRNN_CH_2023feb_fp16.onnx
- models/text_recognition_crnn/text_recognition_CRNN_EN_2023feb_fp16.onnx
Part two of https://github.com/opencv/opencv_zoo/issues/165
> Add back CRNN FP16 models as git-lfs tracked files

- models/handpose_estimation_mediapipe/README.md
- models/handpose_estimation_mediapipe/demo.py
- models/handpose_estimation_mediapipe/example_outputs/gesture_classification.png
This PR follows https://github.com/opencv/opencv_zoo/pull/139 . This implementation is a simple version, It's just for demostration.
Partially resolves https://github.com/opencv/opencv_zoo/issues/127 
Add handpose estimation (0-9)
> Add gesture classification for handpose estimation

- models/text_detection_db/CMakeLists.txt
- models/text_detection_db/README.md
- models/text_detection_db/demo.cpp
Next example text detection model DB in C++
> Text Detection model DB

- models/handpose_estimation_mediapipe/mp_handpose.py
Fixes bug #181 
palm box is `((x1, y1), (x2, y2))`, so it should be clipped to `(image.shape[1], image.shape[0])`
> HandPose Estimation: clip palm bbox to (width, height)

- models/object_detection_yolox/CMakeLists.txt
- models/object_detection_yolox/README.md
- models/object_detection_yolox/demo.cpp
Yolox in c++
Option v and s are not used in demo.py
Values mean and std are not used too in demo.py
I think blobFromImageWithParams can be used but it will not give same result: 
border is set to 0 (not 114) and crop is done relative to image center (not (0,0) )
> yolox in c++

- README.md
- models/face_recognition_sface/README.md
- models/face_recognition_sface/demo.py
- models/face_recognition_sface/example_outputs/demo.jpg
- models/face_recognition_sface/sface.py
> Add SFace visualization demo and example outputs

- models/facial_expression_recognition/CMakeLists.txt
- models/facial_expression_recognition/README.md
- models/facial_expression_recognition/demo.cpp
This Pull Request introduces a C++ demo for utilizing and visualizing the Facial Expression Recognition (FER) model requested in issue #135 . The changes include:
- `demo.cpp`: This file contains the demo implementation, featuring a class `YuNet` for face detection (adapted from `face_detection_yunet/demo.cpp` to create a stand-alone demo) and a class `FER` for preprocessing and inference with the Facial Expression Recognition model.
- `CMakeLists.txt`: The related CMakeLists file necessary for building the program.
- `README.md`: The README file has been updated to include information about this new demo.
The demo offers two modes of inference: real-time using the camera or processing a static image.
The coding style in `demo.cpp` aligns with the conventions used in other demos and …
> C++ Demo - Facial Expression Recognition

- tools/quantize/quantize-ort.py
Resolve #239
Running the quantization script `quantize-ort.py` cannot reproduce the quantized model in the repo. The current script will produce int8 quantized ppresnet50 at a size of over 120 MB, which is significantly different from the existing quantized models in the repo at the size of ~26 MB. After some investigation, I think the reason might be that preprocessing is missing. [The ONNX documentation](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#qdqdebug) seems to suggest preprocessing is highly encouraged.
Left: Computation graph of already quantized models in the repo or models quantized by the updated script.
Right: Computation graph of the model quantized by the original script.<br>
We can see that the current script will result in a model with an …
> Introduce Preprocessing for Optimized Quantization in `quantize-ort.py`

- models/object_tracking_vittrack/demo.py
- models/optical_flow_estimation_raft/demo.py
This PR addresses compatibility issues with OpenCV version 4.9.0 by updating assertions in the code. Issue was pointed out in https://github.com/opencv/opencv_zoo/issues/135#issuecomment-1962323969. 
Additionally, a minor adjustment has been made to increase the offset, preventing the confidence text from overlapping with the bounding box border.
> Fix OpenCV version assertions in ViTTrack & RAFT and text offset

- models/object_detection_nanodet/CMakeLists.txt
- models/object_detection_nanodet/README.md
- models/object_detection_nanodet/demo.cpp
This PR adds the CPP equivalent version `demo.cpp` of the existing Python demo for the NanoDet object detection model. The `README` is correspondingly updated. The interface matches other cpp demos within the set of ML models. The C++ demo more than doubles the FPS of the equivalent Python demo for a video feed.
Average FPS on my laptop (AMD Ryzen 7 5800H) for a (640 x 480) webcam feed:
- Python: 10 FPS
- C++: 25 FPS
**Input**
**C++**
Command: `./build/opencv_zoo_object_detection_nanodet -i=scene.jpg`
**Python**
Command: `python3 demo.py -i scene.jpg`
**C++**
Command: `./build/opencv_zoo_object_detection_nanodet`
**Python**
Command: `python3 demo.py`
**C++**
```
Mat infer(const Mat& sourceImage)
{
cout << "sourceImage - shape | type | first value | 3rd value" << endl;
cout << …
```
> C++ Demo - Object Detection (NanoDet)

- models/text_detection_ppocr/demo.cpp
Minor PR to correct the default model path and address issues with visualization. The issue was partially discussed in https://github.com/opencv/opencv_zoo/issues/135#issuecomment-1962323969.
> Fix visualization and default model for text detection PP-OCR

- models/face_detection_yunet/demo.cpp
- models/image_classification_mobilenet/demo.cpp
- models/object_detection_nanodet/demo.cpp
- models/object_detection_nanodet/demo.py
- models/object_detection_yolox/demo.cpp
- models/object_detection_yolox/demo.py
- models/person_detection_mediapipe/demo.cpp
- models/pose_estimation_mediapipe/demo.cpp
- models/text_detection_ppocr/demo.cpp
- models/text_recognition_crnn/demo.cpp
- models/text_recognition_crnn/demo.py
Minor PR fixing spelling mistakes, spacing, and removed unused variables. Issue partially mentioned in https://github.com/opencv/opencv_zoo/issues/135#issuecomment-1962323969.
> Fix spelling, spacing, and unused variables

- models/object_tracking_vittrack/CMakeLists.txt
- models/object_tracking_vittrack/README.md
- models/object_tracking_vittrack/demo.cpp
- models/object_tracking_vittrack/demo.py
This PR adds the C++ demo for the Object Tracking VitTrack model, as part of a request from https://github.com/opencv/opencv_zoo/issues/135.
- `demo.cpp`: Added to have matching functionality to the `demo.py`, text offsets in both versions were adjusted to prevent overlap and improve clarity.
- `demo.py`: Updated to use save and vis flags for optional saving (disabled by default) and visualization (enabled by default) functionality.
- `CMakeLists.txt`: Created to build with OpenCV 4.9.0 and enforces C++11 standards upon building.
- `README.md`: Updated with C++ instructions.
The interface matches other C++ demos within the set of ML models.
Average 100+ FPS on my laptop (AMD Ryzen 7 5800H) for a (640 x 480) webcam feed. FPS is slightly higher on a (1273 x 733) input video, see testing …
> C++ Demo - Object Tracking (VitTrack)

- models/face_recognition_sface/CMakeLists.txt
- models/face_recognition_sface/README.md
- models/face_recognition_sface/demo.cpp
This pull request adds a C++ demo for the SFace recognizer requested in https://github.com/opencv/opencv_zoo/issues/135.
* ```README.md``` was updated to include basic instructions for compiling and running the C++ demo.
* ```CMakeLists.txt``` contains the cmake code necessary for building the C++ demo.
* ```demo.cpp``` contains the source for the C++ demo.
The demo has two available modes.
**_Static Images_**: the user provides a target image (left), and a query image (right). 
**_Dynamic Webcam_**: the user provides a target image (left), and webcam is used for the query image (right).
> C++ Demo SFace Recognizer

- models/face_detection_yunet/yunet.py
With the current opencv-python and numpy packages. Executing the eval script will crash with error:
```
"...\datasets\widerface.py", line 305, in eval
det = np.append(np.around(det[:, :4], 1), np.around(det[:, -1], 3).reshape(-1, 1), axis=1)
~~~^^^^^^^
IndexError: index -1 is out of bounds for axis 1 with size 0
```
The returning `np.empty(shape=(0, 5))` instead of `np.arrayy([])` for empty detections will fix this.
> Bugfix: Crash during Evaluation of Yunet on Widerface Dataset

- tools/quantize/README.md
- tools/quantize/block_quantize.py
- tools/quantize/requirements.txt
This PR introduces a Python tool for block quantizing ONNX models. The quantized models adhere to the ONNX standard, verified using `onnx.checker.check_model(self.model, full_check=True)`.
Additionally, these block-quantized models are compatible with the `QuantizeLinear` and `DequantizeLinear` layers in OpenCV, as introduced in opencv/opencv#25644, allowing them to be executed within the OpenCV DNN engine.
The tool currently performs asymmetric weight-only quantization on Convolutional Layers. It's possible to specify the desired quantization block size.
The quantization is applied along axis 1, flattening convolutional weights $[C_{out}, C_{in}, K_w, K_h] \rightarrow [C_{out}, C_{in} \times K_w \times K_h]$. 
Future enhancements could extend the tool capabilities, making it more …
> [GSoC] Blockwise Quantization Tool

- tools/quantize/block_quantize.py
This PR enhances the block quantization tool by supporting `Gemm` and `MatMul` layers.
The code has been refactored to make it more general and handle side cases, in particular:
- All the `axis = 1` specific instructions have been modified to support any.
- Handled the case of parameter sharing (when multiple layers share the same set of weights)
The effectiveness and correctness of the tool were tested on the following models:
-  [Vit_b_32](https://dl.opencv.org/models/vit/vit_b_32.onnx) containing both `MatMul` and `Gemm`.
-  [object_tracking_vittrack](https://github.com/opencv/opencv_zoo/blob/main/models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx) containing `MatMul`  and parameter sharing across different layers. This model inference has also been tested using …
> [GSoC] Gemm and MatMul block quantization support

- models/person_reid_youtureid/CMakeLists.txt
- models/person_reid_youtureid/README.md
- models/person_reid_youtureid/demo.cpp
This pull request adds a C++ demo for the person_reid_youtureid requested in #135 
- `README.md` was updated to include basic instructions for compiling and running the C++ demo.
- `CMakeLists.txt` contains the cmake code necessary for building the C++ demo.
- `demo.cpp` contains the source code for the C++ demo.
(test data comes from [https://github.com/ReID-Team/ReID_extra_testdata](https://github.com/ReID-Team/ReID_extra_testdata))
one little problem is that cpp17 is needed for directory access
> C++ Demo for person_reid_youtureid

- models/qrcode_wechatqrcode/CMakeLists.txt
- models/qrcode_wechatqrcode/README.md
- models/qrcode_wechatqrcode/demo.cpp
Added a C++ demo for WeChatQRCode as per #135.
Files added/changed: `demo.cpp`, `CMakeLists.txt` and `README.md`.
**Edit:** Following the convention, I've refactored the code to be class based.
> feat: add cpp demo for wechatqrcode
